CONFIG_LOG=y
<<<<<<< HEAD
CONFIG_TMI_DRIVER_XGZP6897D=y
=======
CONFIG_CUSTOM_XGZP6897D=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
>>>>>>> 745bcf5 (drivers: xgzp6897d: add dualport pressure sensor)
