

# Enable the serial console for printf
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# Enable the SPI bus
CONFIG_SPI=y

# Enable the sensor subsystem and the LSM6DSV16X driver
CONFIG_SENSOR=y
CONFIG_LSM6DSV16X=y
# Specify that we are communicating over SPI, not I2C
CONFIG_LSM6DSV16X_TRIGGER_NONE=y

CONFIG_LOG=y
# CONFIG_SPI_LOG_LEVEL_DBG=y
# CONFIG_SENSOR_LOG_LEVEL_DBG=y
# CONFIG_UART_USE_RUNTIME_CONFIGURE=y